### ISSUE TITLE
Pesan terkadang tidak dapat terkirim ke group

### ISSUE THREAD

**Issue by ahmadkeren** [DikaArdnt/Hisoka-Morou#101]
Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa..
Kalau chat pribadi gak ada masalah..
#methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon..
#errornya kadang-kadang muncul kadang enggak

**Comment by JunaGanz** [comment]
> Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak

Iya saya juga pernah ngalamin error kayak gitu, kalau mau normal lagi bot nya harus di restart. Yang jadi masalah itu letak error nya gak ketauan:(

**Comment by DikaArdnt** [comment]
> Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak

Scnya jelek bang, makanya jangan dipake

**Comment by KunzxD404** [comment]
> Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak

Ss errornya

**Comment by FatihArridho** [comment]
> > Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak
> 
> Scnya jelek bang, makanya jangan dipake
> 
> Biasanya sih karena loading prekeys dulu, kekurangan socket sih mending kalian make puppeteer

Betul scnya jelek:)

**Comment by ahmadkeren** [comment]
> > Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak
> 
> Ss errornya

errornya bisa dibilang gak ada, try catch pun gak nangkap hasil errornya..
kalau dibiarin (gak direstart ataupun sejenisnya) nanti lama-lama bisa sendiri (ngirim pesan ke group)..
#note: kalau ngirim pesan pribadi gak ada masalah sama sekali.

**Comment by ahmadkeren** [comment]
> > Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak
> 
> Ss errornya

kalau m.reply di console, cuma dapat "undefined" (bahkan kalau pesan masuk pun, balesannya undefined)..Cuma 
---------
exec: async(conn, m, { commands, args, prefix, text, toUpper }) => {
        return m.reply('ping')
    }
--------
reply gitu aja kalo di group kadang gak mau kekirim..

**Comment by ahmadkeren** [comment]
> > > > Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa.. Kalau chat pribadi gak ada masalah.. #methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon.. #errornya kadang-kadang muncul kadang enggak
> > > 
> > > 
> > > Ss errornya
> > 
> > 
> > ## kalau m.reply di console, cuma dapat "undefined" (bahkan kalau pesan masuk pun, balesannya undefined)..Cuma
> > ## exec: async(conn, m, { commands, args, prefix, text, toUpper }) => {
> > return m.reply('ping')
> > }
> > reply gitu aja kalo di group kadang gak mau kekirim..
> 
> Lu pakai sc siaapa dah, perasaan eval m.reply ga seribet itu dan sc hisoka gua coba gada eror sama sekali. Coba run di hosting biar cepet

Asumsi sekarang: bugs dari MD baileysnya..
Diriku gak make sc hisoka.. cuma karena hisoka juga make modul baileys, makanya diriku coba nanya disini mana tau ada yang pernah ngalamin dan dapat solusi...

![Screen Shot 2022-05-08 at 09 43 10](https://user-images.githubusercontent.com/49072140/167279518-1970db78-527c-4c6c-b100-8b5ea8261753.png)
