### ISSUE TITLE
Autoread 

### ISSUE THREAD

**Issue by dlvash** [DikaArdnt/Hisoka-Morou#110]
Permisi om di sc ni cara matiin autoread ny dimana ya ? 
Makasih

**Comment by JunaGanz** [comment]
> Permisi om di sc ni cara matiin autoread ny dimana ya ? Makasih

// Push Message To Console && Auto Read
        if (m.message) {
            hisoka.sendReadReceipt(m.chat, m.sender, [m.key.id])
            console.log(chalk.black(chalk.bgWhite('[ PESAN ]')), chalk.black(chalk.bgGreen(new Date)), chalk.black(chalk.bgBlue(budy || m.mtype)) + '\n' + chalk.magenta('=> Dari'), chalk.green(pushname), chalk.yellow(m.sender) + '\n' + chalk.blueBright('=> Di'), chalk.green(m.isGroup ? pushname : 'Private Chat', m.chat))
        }


Jadiin Gini

// Push Message To Console && Auto Read
        if (m.message) {
            console.log(chalk.black(chalk.bgWhite('[ PESAN ]')), chalk.black(chalk.bgGreen(new Date)), chalk.black(chalk.bgBlue(budy || m.mtype)) + '\n' + chalk.magenta('=> Dari'), chalk.green(pushname), chalk.yellow(m.sender) + '\n' + chalk.blueBright('=> Di'), chalk.green(m.isGroup ? pushname : 'Private Chat', m.chat))
        }

**Comment by dlvash** [comment]
> 
Okeh om faham bte thanks

**Comment by dlvash** [comment]
> > Permisi om di sc ni cara matiin autoread ny dimana ya ? Makasih
> 
> // Push Message To Console && Auto Read if (m.message) { hisoka.sendReadReceipt(m.chat, m.sender, [m.key.id]) console.log(chalk.black(chalk.bgWhite('[ PESAN ]')), chalk.black(chalk.bgGreen(new Date)), chalk.black(chalk.bgBlue(budy || m.mtype)) + '\n' + chalk.magenta('=> Dari'), chalk.green(pushname), chalk.yellow(m.sender) + '\n' + chalk.blueBright('=> Di'), chalk.green(m.isGroup ? pushname : 'Private Chat', m.chat)) }
> 
> Jadiin Gini
> 
> // Push Message To Console && Auto Read if (m.message) { console.log(chalk.black(chalk.bgWhite('[ PESAN ]')), chalk.black(chalk.bgGreen(new Date)), chalk.black(chalk.bgBlue(budy || m.mtype)) + '\n' + chalk.magenta('=> Dari'), chalk.green(pushname), chalk.yellow(m.sender) + '\n' + chalk.blueBright('=> Di'), chalk.green(m.isGroup ? pushname : 'Private Chat', m.chat)) }

Ok om faham, btw thanks 🙏🙏
