### ISSUE TITLE
scan with web

### ISSUE THREAD

**Issue by Geruays** [DikaArdnt/Hisoka-Morou#127]
![Screenshot_2022-06-18-12-39-34](https://user-images.githubusercontent.com/84316160/174422988-519f0122-2910-4ddf-b5b2-02bfbd4fc9ff.jpg)

kalo gini susah jadi cara scan pake web kek di heroku begimana?

**Comment by FatihArridho** [comment]
Gua pakai cmd aman" aja tuh. Coba pakai cmd buat ambil sessionnya.

**Comment by DikaArdnt** [comment]
> ![Screenshot_2022-06-18-12-39-34](https://user-images.githubusercontent.com/84316160/174422988-519f0122-2910-4ddf-b5b2-02bfbd4fc9ff.jpg)
> 
> kalo gini susah jadi cara scan pake web kek di heroku begimana?

Di minimaze coba

**Comment by Geruays** [comment]
ty bang gw install vnc akhirnya rada lama tapi gpp thanks sarannya
