### ISSUE TITLE
tandai anggota yang tidak aktif

### ISSUE THREAD

**Issue by dypblue** [DikaArdnt/Hisoka-Morou#131]
Halo apa kabarmu? apakah Anda memiliki kasus untuk menandai anggota yang tidak aktif dalam grup?

**Comment by FatihArridho** [comment]
Screenshot sir

**Comment by ianskids** [comment]
Mungkin perlu dicatat terakhir dia mengirim text didalam grup tersebut

**Comment by DikaArdnt** [comment]
> Screenshot sir

Skrinsut skrinsut

**Comment by irham01** [comment]
pahamku sih dia req fitur buat nyari tau member yg gak aktif gitu, mungkin bisa pake jangka waktu terakhir dia chat... maybe

**Comment by FatihArridho** [comment]
Last presence sih
