### ISSUE TITLE
ask?

### ISSUE THREAD

**Issue by irham01** [DikaArdnt/Hisoka-Morou#139]
solusi sering muncul error gini bang

TypeError: Cannot read properties of undefined (reading 'caption')                                                            │
     at exports.smsg (C:\Users\adminisrator\his\lib\myfunc.js:239:50)

        m.body = m.message.conversation || m.msg.caption || m.msg.text || (m.mtype == 'listResponseMessage') && m.msg.singleSelectReply.selectedRowId || (m.mtype == 'buttonsResponseMessage') && m.msg.selectedButtonId || (m.mtype == 'viewOnceMessage') && m.msg.caption || m.text

**Comment by FatihArridho** [comment]
@DikaArdnt

**Comment by iluser** [comment]
jjk, masalah yang sama

**Comment by irham01** [comment]
> jjk, masalah yang sama

sempet nyoba benerin malah tambah error :v
