### ISSUE TITLE
Punten 

### ISSUE THREAD

**Issue by DzOfc** [DikaArdnt/Hisoka-Morou#140]
cara atasi connected open lebih dari 1 jam gimana bang🐦

**Comment by JunaGanz** [comment]
> cara atasi connected open lebih dari 1 jam gimana bang🐦

Gak kebaca pesan yang masuk di conselog nya kah?

**Comment by DzOfc** [comment]
> 

Conselog

**Comment by JunaGanz** [comment]
> 



> > 
> 
> Conselog

Sama bejir gue juga ngalamin pesan yang masuk gak ada di console.log nya gue kira waktu itu gue doang yang ngalamin nya

**Comment by FatihArridho** [comment]
Scan ulang adalah jalan ninjaku
