### ISSUE TITLE
Bad session

### ISSUE THREAD

**Issue by iluser** [DikaArdnt/Hisoka-Morou#145]
saat mengirim pesan di grup dengan jumlah member 200+ terjadi bad session dan bot restart ulang... dan begitupun seterusnya

**Comment by FatihArridho** [comment]
Pakailah baileys github, udah di fix

**Comment by Mr4sR** [comment]
> Pakailah baileys github, udah di fix

Udah pakai bre, tapi kok malah gak bisa ngirim pesan ya botnya (sama kek pas ngirim pesan di group member 200+)
