### ISSUE TITLE
[BUG] error install package.json

### ISSUE THREAD

**Issue by ssh69** [DikaArdnt/Hisoka-Morou#162]
This problem 
![IMG-20220809-WA0029](https://user-images.githubusercontent.com/108958876/183641102-ac64b5f4-bd0a-42c7-9823-fdaefb424f9d.jpg)

**Comment by FatihArridho** [comment]
Try install use yarn

**Comment by ssh69** [comment]
> Try install use yarn

Working fine hmm

**Comment by ssh69** [comment]
![IMG-20220809-WA0006](https://user-images.githubusercontent.com/108958876/183710703-9080ae29-ac41-433e-aecc-cd17f17868d7.jpg)

Error why?

**Comment by FatihArridho** [comment]
use tsc

**Comment by FatihArridho** [comment]
or install module npm @adiwajshing/Baileys version new

**Comment by ssh69** [comment]
Not working
^4.3.0 only working

**Comment by Fjr-api** [comment]
kalau masalah tentang require("chalk") gimana?, katanya erorr karena gk support, harus pake import() tapi pas di coba tetep gk bisa malah not function

**Comment by Xfroz** [comment]
> or install module npm @adiwajshing/Baileys version new

How to install new version??
