### ISSUE TITLE
ini dimana path environment variable untuk ffmpeg? soalnya muncul error di chat wa

### ISSUE THREAD

**Issue by radhealaniesoftware** [DikaArdnt/Hisoka-Morou#164]
# hi im sussiisoniic!
## mau nanya (karena pemula hehe)
ini dimana path environment variable untuk ffmpeg? soalnya muncul **error : cannot find ffmpeg at c:\user\u...** di chat wa
bukti screenshot ada dibawah

###### sussiisoniic, your 1st gfx creators
![Screenshot_20220810-194957](https://user-images.githubusercontent.com/86042978/183894221-4c1014e1-bf97-4a03-8cae-0c33a282db91.jpg)
.

**Comment by shoukosagiri-poi** [comment]
https://youtu.be/IECI72XEox0
