### ISSUE TITLE
Kalo error gini langsung mati BOTnya

### ISSUE THREAD

**Issue by irham01** [DikaArdnt/Hisoka-Morou#165]
![Untitled](https://user-images.githubusercontent.com/77791484/183909502-e9a63768-d17d-4a7c-b665-ad0652457e5f.png)

ini kenapa yah bang?

**Comment by JunaGanz** [comment]
+1

**Comment by DikaArdnt** [comment]
> ![Untitled](https://user-images.githubusercontent.com/77791484/183909502-e9a63768-d17d-4a7c-b665-ad0652457e5f.png)
> 
> ini kenapa yah bang?

process
  .on('unhandledRejection', (reason, p) => {
    console.error(reason, 'Unhandled Rejection at Promise', p);
  })
  .on('uncaughtException', err => {
    console.error(err, 'Uncaught Exception thrown');
    process.exit(1);
  });

Detail : https://stackoverflow.com/questions/40867345/catch-all-uncaughtexception-for-node-js-app
