### ISSUE TITLE
Bug Kirim Command 1 kali balas dua kali

### ISSUE THREAD

**Issue by bolaxd** [DikaArdnt/Hisoka-Morou#176]

**Comment by anubiskun** [comment]
itu masalah di session baru yang ke replace session lama waktu lu push tu bot ke server

**Comment by MatchBox-ID** [comment]
Hallo @anubiskun Saya matchbox-md, apakah ada masalah dari repositori ini? Mungkin saya bisa membantu anda, hubungi matchbox team lewat chat whatsapp di [Sini](https://wa.me/+6285936528795)
