### ISSUE TITLE
use-single-file-auth-state

### ISSUE THREAD

**Issue by irham01** [DikaArdnt/Hisoka-Morou#177]
Error terus mau pindah ke Multi... Help bang

**Comment by irham01** [comment]
@DikaArdnt  @FatihArridho  @anubiskun @JunaGanz

**Comment by anubiskun** [comment]
```js
const { default: makeWASocket, DisconnectReason, useMultiFileAuthState, fetchLatestBaileysVersion } = require("@adiwajshing/baileys");
const {default: logger} = require('@adiwajshing/baileys/lib/Utils/logger');
const { Boom } = require("@hapi/boom");
logger.level = 'silent'
async function start(){
    const { state, saveCreds } = await useMultiFileAuthState('foldernya_ngab')
   

    const anubis = makeWASocket({
        logger,
        printQRInTerminal: true,
        browser: ["Anubis-Bot", "Safari", "1.0.0"],
        auth: state,
    })

    anubis.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update
        if (connection === 'close') {
            DisconnectReason
            let reason = new Boom(lastDisconnect?.error)?.output.statusCode
                if (reason === DisconnectReason.badSession) { console.log(`Bad Session File, Please Delete Session and Scan Again`); anubis.logout(); }
                else if (reason === DisconnectReason.connectionClosed) { console.log("Connection closed, reconnecting...."); start(); }
                else if (reason === DisconnectReason.connectionLost) { console.log("Connection Lost from Server, reconnecting..."); start(); }
                else if (reason === DisconnectReason.connectionReplaced) { console.log("Connection Replaced, Another New Session Opened, Please Close Current Session First"); anubis.logout(); }
                else if (reason === DisconnectReason.loggedOut) { console.log(`Device Logged Out, Please Scan Again And Run.`); anubis.logout(); }
                else if (reason === DisconnectReason.restartRequired) { console.log("Restart Required, Restarting..."); start(); }
                else if (reason === DisconnectReason.timedOut) { console.log("Connection TimedOut, Reconnecting..."); start(); }
                else if (reason === DisconnectReason.Multidevicemismatch) { console.log("Multi device mismatch, please scan again"); anubis.logout(); }
                else hisoka.end(`Unknown DisconnectReason: ${reason}|${connection}`)
            }
        if (update.isOnline) console.log('BOT RUNNING!')
        console.log(update)
        
    })

    anubis.ev.on('messages.upsert', (chatUpdate) => {
        if (chatUpdate){
            for (let i = 0; i < chatUpdate.messages.length; i++){
                console.log(`[ PESAN ] -> ${chatUpdate.messages[i].pushName} => ${chatUpdate.messages[i].message.conversation}`)
            }
        }
    })

    anubis.ev.on('creds.update', saveCreds )
}

start()
```

**Comment by irham01** [comment]
> ```js
> const { default: makeWASocket, DisconnectReason, useMultiFileAuthState, fetchLatestBaileysVersion } = require("@adiwajshing/baileys");
> const {default: logger} = require('@adiwajshing/baileys/lib/Utils/logger');
> const { Boom } = require("@hapi/boom");
> logger.level = 'silent'
> async function start(){
>     const { state, saveCreds } = await useMultiFileAuthState('foldernya_ngab')
>    
> 
>     const anubis = makeWASocket({
>         logger,
>         printQRInTerminal: true,
>         browser: ["Anubis-Bot", "Safari", "1.0.0"],
>         auth: state,
>     })
> 
>     anubis.ev.on('connection.update', async (update) => {
>         const { connection, lastDisconnect } = update
>         if (connection === 'close') {
>             DisconnectReason
>             let reason = new Boom(lastDisconnect?.error)?.output.statusCode
>                 if (reason === DisconnectReason.badSession) { console.log(`Bad Session File, Please Delete Session and Scan Again`); anubis.logout(); }
>                 else if (reason === DisconnectReason.connectionClosed) { console.log("Connection closed, reconnecting...."); start(); }
>                 else if (reason === DisconnectReason.connectionLost) { console.log("Connection Lost from Server, reconnecting..."); start(); }
>                 else if (reason === DisconnectReason.connectionReplaced) { console.log("Connection Replaced, Another New Session Opened, Please Close Current Session First"); anubis.logout(); }
>                 else if (reason === DisconnectReason.loggedOut) { console.log(`Device Logged Out, Please Scan Again And Run.`); anubis.logout(); }
>                 else if (reason === DisconnectReason.restartRequired) { console.log("Restart Required, Restarting..."); start(); }
>                 else if (reason === DisconnectReason.timedOut) { console.log("Connection TimedOut, Reconnecting..."); start(); }
>                 else if (reason === DisconnectReason.Multidevicemismatch) { console.log("Multi device mismatch, please scan again"); anubis.logout(); }
>                 else anubis.end(`Unknown DisconnectReason: ${reason}|${connection}`)
>             }
>         if (update.isOnline) console.log('BOT RUNNING!')
>         console.log(update)
>         
>     })
> 
>     anubis.ev.on('messages.upsert', (chatUpdate) => {
>         if (chatUpdate){
>             for (let i = 0; i < chatUpdate.messages.length; i++){
>                 console.log(`[ PESAN ] -> ${chatUpdate.messages[i].pushName} => ${chatUpdate.messages[i].message.conversation}`)
>             }
>         }
>     })
> 
>     anubis.ev.on('creds.update', saveCreds )
> }
> 
> start()
> ```

gatau cara ubahnya, ngestuck deh :(

**Comment by anubiskun** [comment]
> > ```js
> > const { default: makeWASocket, DisconnectReason, useMultiFileAuthState, fetchLatestBaileysVersion } = require("@adiwajshing/baileys");
> > const {default: logger} = require('@adiwajshing/baileys/lib/Utils/logger');
> > const { Boom } = require("@hapi/boom");
> > logger.level = 'silent'
> > async function start(){
> >     const { state, saveCreds } = await useMultiFileAuthState('foldernya_ngab')
> >    
> > 
> >     const anubis = makeWASocket({
> >         logger,
> >         printQRInTerminal: true,
> >         browser: ["Anubis-Bot", "Safari", "1.0.0"],
> >         auth: state,
> >     })
> > 
> >     anubis.ev.on('connection.update', async (update) => {
> >         const { connection, lastDisconnect } = update
> >         if (connection === 'close') {
> >             DisconnectReason
> >             let reason = new Boom(lastDisconnect?.error)?.output.statusCode
> >                 if (reason === DisconnectReason.badSession) { console.log(`Bad Session File, Please Delete Session and Scan Again`); anubis.logout(); }
> >                 else if (reason === DisconnectReason.connectionClosed) { console.log("Connection closed, reconnecting...."); start(); }
> >                 else if (reason === DisconnectReason.connectionLost) { console.log("Connection Lost from Server, reconnecting..."); start(); }
> >                 else if (reason === DisconnectReason.connectionReplaced) { console.log("Connection Replaced, Another New Session Opened, Please Close Current Session First"); anubis.logout(); }
> >                 else if (reason === DisconnectReason.loggedOut) { console.log(`Device Logged Out, Please Scan Again And Run.`); anubis.logout(); }
> >                 else if (reason === DisconnectReason.restartRequired) { console.log("Restart Required, Restarting..."); start(); }
> >                 else if (reason === DisconnectReason.timedOut) { console.log("Connection TimedOut, Reconnecting..."); start(); }
> >                 else if (reason === DisconnectReason.Multidevicemismatch) { console.log("Multi device mismatch, please scan again"); anubis.logout(); }
> >                 else anubis.end(`Unknown DisconnectReason: ${reason}|${connection}`)
> >             }
> >         if (update.isOnline) console.log('BOT RUNNING!')
> >         console.log(update)
> >         
> >     })
> > 
> >     anubis.ev.on('messages.upsert', (chatUpdate) => {
> >         if (chatUpdate){
> >             for (let i = 0; i < chatUpdate.messages.length; i++){
> >                 console.log(`[ PESAN ] -> ${chatUpdate.messages[i].pushName} => ${chatUpdate.messages[i].message.conversation}`)
> >             }
> >         }
> >     })
> > 
> >     anubis.ev.on('creds.update', saveCreds )
> > }
> > 
> > start()
> > ```
> 
> gatau cara ubahnya, ngestuck deh :(

https://github.com/anubiskun/anubisbot-MD/blob/d960608dac18f242805ccc7c4eff8ba0d07b0845/anubis.js#L81

**Comment by irham01** [comment]
> 
> https://github.com/anubiskun/anubisbot-MD/blob/d960608dac18f242805ccc7c4eff8ba0d07b0845/anubis.js#L81

error mulu, gamau muncul QR nya

**Comment by anubiskun** [comment]
> > https://github.com/anubiskun/anubisbot-MD/blob/d960608dac18f242805ccc7c4eff8ba0d07b0845/anubis.js#L81
> 
> error mulu, gamau muncul QR nya
npm install qrcode-terminal
kalo ga muncul QR nya

**Comment by irham01** [comment]
> npm install qrcode-terminal kalo ga muncul QR nya

Enggak itunya bang, mungkin salah kodenya, hehe
Ntar aja deh nunggu dev nya update 😹
Btw makasih bang, udah diarahin

**Comment by FatihArridho** [comment]
turu, malas apdet lgi skit

**Comment by anubiskun** [comment]
> > npm install qrcode-terminal kalo ga muncul QR nya
> 
> Enggak itunya bang, mungkin salah kodenya, hehe Ntar aja deh nunggu dev nya update 😹 Btw makasih bang, udah diarahin

wkwk shaap

**Comment by anubiskun** [comment]
> turu, malas apdet lgi skit

turu bae turu

**Comment by irham01** [comment]
> turu, malas apdet lgi skit

Semoga lekas sembuh bang, gak bisa move on dari sc ini 😹
Lagi nyoba nyoba pake scnya bang @anubiskun

**Comment by anubiskun** [comment]
> > turu, malas apdet lgi skit
> 
> Semoga lekas sembuh bang, gak bisa move on dari sc ini 😹 Lagi nyoba nyoba pake scnya bang @anubiskun

iya SC gw juga terinspirasi dari sc Hisoka-Morou hampir banyak yang mirip kok

**Comment by irham01** [comment]
> iya SC gw juga terinspirasi dari sc Hisoka-Morou hampir banyak yang mirip kok

Iya bener, sempet nyoba kemaren tapi gak work, pas tadi siang update baru bisa, tapi belum aku buka satu satu filenya, alhasil db masih ilang ilangan

**Comment by anubiskun** [comment]
> > iya SC gw juga terinspirasi dari sc Hisoka-Morou hampir banyak yang mirip kok
> 
> Iya bener, sempet nyoba kemaren tapi gak work, pas tadi siang update baru bisa, tapi belum aku buka satu satu filenya, alhasil db masih ilang ilangan

soal db gw saranin jangan run pake database.json/localdb kalo bisa lu bikin mongodb soalnya ada bug di localdb waktu save

**Comment by irham01** [comment]
> soal db gw saranin jangan run pake database.json/localdb kalo bisa lu bikin mongodb soalnya ada bug di localdb waktu save

Ooh pantesan, pernah pake mongodb gak bisa nyimpen note berupa audio (pake sc hisoka), ntar aku coba coba lagi bang,

**Comment by anubiskun** [comment]
> > soal db gw saranin jangan run pake database.json/localdb kalo bisa lu bikin mongodb soalnya ada bug di localdb waktu save
> 
> Ooh pantesan, pernah pake mongodb gak bisa nyimpen note berupa audio (pake sc hisoka), ntar aku coba coba lagi bang,

kalo di SC gw bisa coba bae

**Comment by irham01** [comment]
> kalo di SC gw bisa coba bae

oke bang nanti tak coba coba

**Comment by arifintajul4** [comment]
> ```js
> const { default: makeWASocket, DisconnectReason, useMultiFileAuthState, fetchLatestBaileysVersion } = require("@adiwajshing/baileys");
> const {default: logger} = require('@adiwajshing/baileys/lib/Utils/logger');
> const { Boom } = require("@hapi/boom");
> logger.level = 'silent'
> async function start(){
>     const { state, saveCreds } = await useMultiFileAuthState('foldernya_ngab')
>    
> 
>     const anubis = makeWASocket({
>         logger,
>         printQRInTerminal: true,
>         browser: ["Anubis-Bot", "Safari", "1.0.0"],
>         auth: state,
>     })
> 
>     anubis.ev.on('connection.update', async (update) => {
>         const { connection, lastDisconnect } = update
>         if (connection === 'close') {
>             DisconnectReason
>             let reason = new Boom(lastDisconnect?.error)?.output.statusCode
>                 if (reason === DisconnectReason.badSession) { console.log(`Bad Session File, Please Delete Session and Scan Again`); anubis.logout(); }
>                 else if (reason === DisconnectReason.connectionClosed) { console.log("Connection closed, reconnecting...."); start(); }
>                 else if (reason === DisconnectReason.connectionLost) { console.log("Connection Lost from Server, reconnecting..."); start(); }
>                 else if (reason === DisconnectReason.connectionReplaced) { console.log("Connection Replaced, Another New Session Opened, Please Close Current Session First"); anubis.logout(); }
>                 else if (reason === DisconnectReason.loggedOut) { console.log(`Device Logged Out, Please Scan Again And Run.`); anubis.logout(); }
>                 else if (reason === DisconnectReason.restartRequired) { console.log("Restart Required, Restarting..."); start(); }
>                 else if (reason === DisconnectReason.timedOut) { console.log("Connection TimedOut, Reconnecting..."); start(); }
>                 else if (reason === DisconnectReason.Multidevicemismatch) { console.log("Multi device mismatch, please scan again"); anubis.logout(); }
>                 else anubis.end(`Unknown DisconnectReason: ${reason}|${connection}`)
>             }
>         if (update.isOnline) console.log('BOT RUNNING!')
>         console.log(update)
>         
>     })
> 
>     anubis.ev.on('messages.upsert', (chatUpdate) => {
>         if (chatUpdate){
>             for (let i = 0; i < chatUpdate.messages.length; i++){
>                 console.log(`[ PESAN ] -> ${chatUpdate.messages[i].pushName} => ${chatUpdate.messages[i].message.conversation}`)
>             }
>         }
>     })
> 
>     anubis.ev.on('creds.update', saveCreds )
> }
> 
> start()
> ```

<img width="1440" alt="Screenshot 2024-11-01 at 14 45 50" src="https://github.com/user-attachments/assets/ca52d04c-3749-4b97-9bf2-463f6ae67194">
info bang, update kah?
