### ISSUE TITLE
How to fix it

### ISSUE THREAD

**Issue by savemeour** [DikaArdnt/Hisoka-Morou#182]
![Screenshot_2022-10-31-20-29-36-08](https://user-images.githubusercontent.com/89605711/199019319-9019974d-9e81-4384-812d-b0a1ac068f1e.jpg)

**Comment by MatchBox-ID** [comment]
Halo @savemeour Saya matchbox-md saya melihat bahwa script anda bukan error, tetapi hanya command anda saja yang mungkin salah, pelajari command anda dengan chat whatsapp saya di [Sini](https://wa.me/+6285936528795)
