### ISSUE TITLE
Lucu banh

### ISSUE THREAD

**Issue by DikaArdnt** [DikaArdnt/Hisoka-Morou#2]
![Screenshot_2021-12-05-23-37-16-21](https://user-images.githubusercontent.com/88322331/144757034-d1c6e387-273a-43d4-8826-c0ab2498fc9a.jpg)

**Comment by Hisoka775** [comment]
> ![Screenshot_2021-12-05-23-37-16-21](https://user-images.githubusercontent.com/88322331/144757034-d1c6e387-273a-43d4-8826-c0ab2498fc9a.jpg)

mana bisa gitu anjg

**Comment by scoder37** [comment]
astaga

**Comment by AnDykProgate** [comment]
Awokawokawok

**Comment by KilersBotz** [comment]
## anjir

**Comment by rizky-prasetya** [comment]
Parah aowkwowka

**Comment by YudaXwer** [comment]
Pengbokep hangdal
