### ISSUE TITLE
Sedang menunggu update 🙇

### ISSUE THREAD

**Issue by abclimadasar** [DikaArdnt/Hisoka-Morou#206]
@DikaArdnt @Hisoka775

**Comment by DikaArdnt** [comment]
> @DikaArdnt @Hisoka775

Untuk projek wawebjs ketar-ketir leptop saya, size gede

**Comment by abclimadasar** [comment]
> > @DikaArdnt @Hisoka775
> 
> Untuk projek wawebjs ketar-ketir leptop saya, size gede

Baiklah tidak jadi pindah dari Baileys
