### ISSUE TITLE
bang boleh update fitur ga

### ISSUE THREAD

**Issue by NadhiraAlifah** [DikaArdnt/Hisoka-Morou#21]

**Comment by DikaArdnt** [comment]
> _No description provided._

Ya

**Comment by NadhiraAlifah** [comment]
tapi bang , ada wa ga ? biar enak bicaranya

**Comment by DikaArdnt** [comment]
> tapi bang , ada wa ga ? biar enak bicaranya

https://wa.me/6288292024190

**Comment by NadhiraAlifah** [comment]
ga bisa bang wa nya

**Comment by NadhiraAlifah** [comment]
wa saya aja bang . wa.me/6281414046576

**Comment by Fakermadan** [comment]
Yah
![Uploading 27a875c28b817e2c48c341f55f27a9e2.jpg…]()
