### ISSUE TITLE
Error Starting.

### ISSUE THREAD

**Issue by swatky** [DikaArdnt/Hisoka-Morou#22]
![image](https://user-images.githubusercontent.com/40281950/152061603-88cb4926-6043-46b1-98d3-7ed8ff92b27b.png)

Hello, I'm having a problem trying to start the bot, this error appears, how can I fix it?

**Comment by FatihArridho** [comment]
Install ulang coba

**Comment by DikaArdnt** [comment]
> ![image](https://user-images.githubusercontent.com/40281950/152061603-88cb4926-6043-46b1-98d3-7ed8ff92b27b.png)
> 
> Hello, I'm having a problem trying to start the bot, this error appears, how can I fix it?

remove package baileys then reinstall

**Comment by swatky** [comment]
> 

I tried but the error still persists.

**Comment by FatihArridho** [comment]
> > 
> 
> I tried but the error still persists.

**Comment by FatihArridho** [comment]
> > 
> 
> I tried but the error still persists.

Try install in termux bro
