### ISSUE TITLE
tutor bang

### ISSUE THREAD

**Issue by Niskata** [DikaArdnt/Hisoka-Morou#23]
![image](https://user-images.githubusercontent.com/74761905/152466667-a3b56300-824f-4f8c-ab12-8c5d8fc849ee.png)

**Comment by FatihArridho** [comment]
> ![image](https://user-images.githubusercontent.com/74761905/152466667-a3b56300-824f-4f8c-ab12-8c5d8fc849ee.png)

Udah tsc -p ./node_modules/@adiwajshing/baileys/ belom bang

**Comment by Niskata** [comment]
> Udah tsc -p ./node_modules/@adiwajshing/baileys/ belom bang

> gabisa bang w pake replit

**Comment by FatihArridho** [comment]
> > Udah tsc -p ./node_modules/@adiwajshing/baileys/ belom bang
> 
> gabisa bang w pake replit

bisa tapi?

**Comment by Niskata** [comment]
b> > > Udah tsc -p ./node_modules/@adiwajshing/baileys/ belom bang
> > 
> > 
> > gabisa bang w pake replit
> 
> bisa tapi?
gabisa

**Comment by FatihArridho** [comment]
> > > > Udah tsc -p ./node_modules/@adiwajshing/baileys/ belom bang
> > > 
> > > 
> > > gabisa bang w pake replit
> > 
> > 
> > bisa tapi?
> > gabisa

Coba lu run termux terus deploy di heroku, soalnya gw user heroku enjoyers
