### ISSUE TITLE
add feature antilink

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#31]
_add this feature makes it easier for people to organize their groups_

**Comment by DikaArdnt** [comment]
> _add this feature makes it easier for people to organize their groups_

let linkRegex = /chat.whatsapp.com/([0-9A-Za-z]{20,24})/i
if (linkRegex.exec(m.text)) {
hisoka.groupParticipantsUpdate(m.chat, [m.sender], 'remove')
}

you can add your own in your script

**Comment by Bintangp02** [comment]
Di bagaian aman saya menambahkan?
where do I add?
