### ISSUE TITLE
Tiktok update

### ISSUE THREAD

**Issue by LilSadPanda** [DikaArdnt/Hisoka-Morou#37]
https://github.com/DikaArdnt/Hisoka-Morou/blob/42ea6d2caa7c7bd31c522f6f4c123fa696489118/hisoka.js#L1720
https://github.com/DikaArdnt/Hisoka-Morou/blob/42ea6d2caa7c7bd31c522f6f4c123fa696489118/hisoka.js#L1738
https://github.com/DikaArdnt/Hisoka-Morou/blob/42ea6d2caa7c7bd31c522f6f4c123fa696489118/hisoka.js#L1756

Needs to be updated from 
`let anu = await fetchJson(api('zenz', '/api/downloader/tiktok', { url: text }, 'apikey'))`
to
`let anu = await fetchJson(api('zenz', '/downloader/tiktok', { url: text }, 'apikey'))`

**Comment by FatihArridho** [comment]
tqs
