### ISSUE TITLE
Error after scanned qr code!

### ISSUE THREAD

**Issue by DineshValor** [DikaArdnt/Hisoka-Morou#39]
[
![Screenshot_20220219-234529](https://user-images.githubusercontent.com/98645523/154813696-592fb893-ca09-4b8c-ab52-f6664e65f82f.jpg)
](url)

**Comment by FatihArridho** [comment]
Use pm2 or forever so as not to die.

**Comment by DineshValor** [comment]
> Use pm2 or forever so as not to die.

Pm2 mean personal message?

**Comment by FatihArridho** [comment]
> > Use pm2 or forever so as not to die.
> 
> Pm2 mean personal message?

Cek file Procfile

**Comment by DineshValor** [comment]
> > > Use pm2 or forever so as not to die.
> > 
> > 
> > Pm2 mean personal message?
> 
> Cek file Procfile

Thanks, its working now, but can you tell me where should i can edit in "Procfile" to add mongodb server link to save bot database there!?
