### ISSUE TITLE
How to stop auto seen messages?

### ISSUE THREAD

**Issue by DineshValor** [DikaArdnt/Hisoka-Morou#40]
Didn't found any command to stop auto seen message, even didn't receive messages notification on whatsapp mobile version.
Is there any solution to fix it?

**Comment by DikaArdnt** [comment]
> Didn't found any command to stop auto seen message, even didn't receive messages notification on whatsapp mobile version. Is there any solution to fix it?

https://github.com/DikaArdnt/Hisoka-Morou/blob/master/hisoka.js#L71

delete it
