### ISSUE TITLE
[ISSUE] Video downloader not playable!

### ISSUE THREAD

**Issue by DineshValor** [DikaArdnt/Hisoka-Morou#43]
.play <song/video name>

Video buttons replied:-

Video received but not working/playable.

Audio button replied:-
Response slow, please update its server as well.

**Comment by FatihArridho** [comment]
can send proof of screen shot?

**Comment by DineshValor** [comment]
https://user-images.githubusercontent.com/98645523/154965517-b77ff000-ae54-4d69-9b9e-f288b20b2132.mp4

**Comment by DineshValor** [comment]
> can send proof of screen shot?

Yeah sure you can check above screen recorded.

**Comment by FatihArridho** [comment]
Maybe I'll fix it later, thanks for the report :D
