### ISSUE TITLE
[REQUEST] (Youtube) Reduce video download resolution!

### ISSUE THREAD

**Issue by DineshValor** [DikaArdnt/Hisoka-Morou#45]
Video's currently downloading in max resolution which cause most of the video not downloadable due to it's large size.
My opinion and request is set  resolution to 360p, so almost every song/video can receive without any cause.

**Comment by FatihArridho** [comment]
I will update later, so please be patient and understand.

**Comment by FatihArridho** [comment]
And one more thing, don't spam the issue here, please discuss it first!

**Comment by DineshValor** [comment]
> And one more thing, don't spam the issue here, please discuss it first!

Sorry about that
