### ISSUE TITLE
[EROR] SEMUA BERKAITAN DENGAN TIKTOK

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#46]
[ PESAN ] Tue Feb 22 2022 12:52:07 GMT+0000 (Coordinated Universal Time) .tiktoknowm https://vt.tiktok.com/zsecpeq9c
=> Dari Jenn 628xxxxxxxxxxxx@s.whatsapp.net
=> Di Jenn 628xxxxxxxxxxx@g.us
/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196
if (item.url.toString().startsWith('[http://'](http://%27/);) || item.url.toString().startsWith('[https://'](https://%27/);)) {
^
TypeError: Cannot read properties of undefined (reading 'toString')
at Object.getStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18)
at Object.encryptedStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44)
at Object.prepareWAMessageMedia (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132)
at Object.generateWAMessageContent (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:27)
at Object.generateWAMessage (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:68)
at Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:47)
at hisoka (/bin.js:1764:24)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

``` 
beritahu yangharus gw lakukan
```

**Comment by DikaArdnt** [comment]
> [ PESAN ] Tue Feb 22 2022 12:52:07 GMT+0000 (Coordinated Universal Time) .tiktoknowm https://vt.tiktok.com/zsecpeq9c => Dari Jenn [628xxxxxxxxxxxx@s.whatsapp.net](mailto:628xxxxxxxxxxxx@s.whatsapp.net) => Di Jenn [628xxxxxxxxxxx@g.us](mailto:628xxxxxxxxxxx@g.us) /node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196 if (item.url.toString().startsWith('[http://'](http://%27/);) || item.url.toString().startsWith('[https://'](https://%27/);)) { ^ TypeError: Cannot read properties of undefined (reading 'toString') at Object.getStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18) at Object.encryptedStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44) at Object.prepareWAMessageMedia (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132) at Object.generateWAMessageContent (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:27) at Object.generateWAMessage (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:68) at Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:47) at hisoka (/bin.js:1764:24) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> ```
> beritahu yangharus gw lakukan
> ```

Yang pertama diperhatikan adalah apakah rest api sedang error atau tidak, yang kedua adalah anda memiliki apikey atau tidak, yang ketiga adalah cek apakah limit dari apikey sudah mencapai batas (kalo ada apikey)

**Comment by Bintangp02** [comment]
> > [ PESAN ] Tue Feb 22 2022 12:52:07 GMT+0000 (Coordinated Universal Time) .tiktoknowm https://vt.tiktok.com/zsecpeq9c => Dari Jenn [628xxxxxxxxxxxx@s.whatsapp.net](mailto:628xxxxxxxxxxxx@s.whatsapp.net) => Di Jenn [628xxxxxxxxxxx@g.us](mailto:628xxxxxxxxxxx@g.us) /node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196 if (item.url.toString().startsWith('[http://'](http://%27/);) || item.url.toString().startsWith('[https://'](https://%27/);)) { ^ TypeError: Cannot read properties of undefined (reading 'toString') at Object.getStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18) at Object.encryptedStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44) at Object.prepareWAMessageMedia (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132) at Object.generateWAMessageContent (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:27) at Object.generateWAMessage (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:68) at Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:47) at hisoka (/bin.js:1764:24) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > ```
> > beritahu yangharus gw lakukan
> > ```
> 
> Yang pertama diperhatikan adalah apakah rest api sedang error atau tidak, yang kedua adalah anda memiliki apikey atau tidak, yang ketiga adalah cek apakah limit dari apikey sudah mencapai batas (kalo ada apikey)

bruh lo tahu ??

/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290
throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
^
Error: bad-request
at Object.assertNodeErrorFree (/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
at query (/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:24)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async groupMetadata (/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
at async /node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41
at async Promise.all (index 0)
at async /node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51
at async Object.transaction (/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:78:21)
at async relayMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9)
at async Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:395:17) {
data: 400,
isBoom: true,
isServer: true,
output: {
statusCode: 500,
payload: {
statusCode: 500,
error: 'Internal Server Error',
message: 'An internal server error occurred'
},
headers: {}
}
}

**Comment by FatihArridho** [comment]
Baileys ga semulus & sesempurna yang lu bayangin. Makanya run di heroku/pakai pm2
