### ISSUE TITLE
Help bang

### ISSUE THREAD

**Issue by Rmdhn-20** [DikaArdnt/Hisoka-Morou#48]
In-ini kenapa ya bang... Helpp
![Screenshot_2022-02-23-19-15-15-366_com termux](https://user-images.githubusercontent.com/76412415/155318061-528d2d8c-f63d-4b3d-a436-eb914ccbe8ed.jpg)

**Comment by FatihArridho** [comment]
Biasalah module baileys error, mau module yg ga eror gak pc gw klik disini
