### ISSUE TITLE
Md Belum stable Ya bang

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#49]
```
Punya ku sering mati ngk jelas bang 🗿
```

**Comment by FandyyyDev** [comment]
> ```
> Punya ku sering mati ngk jelas bang 🗿
> ```

Faktor face Banh wkwk

**Comment by Bintangp02** [comment]
> > ```
> > Punya ku sering mati ngk jelas bang 🗿
> > ```
> 
> Kalo stabil saya udah jualan bang

Waduh buat toko aja bang wkwk🤣
Bang email lu apa?
Gw wa baik baik ngak di bales wkwk

**Comment by FandyyyDev** [comment]
> > > ```
> > > Punya ku sering mati ngk jelas bang 🗿
> > > ```
> > 
> > 
> > Kalo stabil saya udah jualan bang
> 
> Waduh buat toko aja bang wkwk🤣 Bang email lu apa? Gw wa baik baik ngak di bales wkwk

Kurang salam nya banh

**Comment by FatihArridho** [comment]
> > > > ```
> > > > Punya ku sering mati ngk jelas bang 🗿
> > > > ```
> > > 
> > > 
> > > Kalo stabil saya udah jualan bang
> > 
> > 
> > Waduh buat toko aja bang wkwk🤣 Bang email lu apa? Gw wa baik baik ngak di bales wkwk
> 
> Kurang salam nya banh

2

**Comment by Bintangp02** [comment]
> > > > > ```
> > > > > Punya ku sering mati ngk jelas bang 🗿
> > > > > ```
> > > > 
> > > > 
> > > > Kalo stabil saya udah jualan bang
> > > 
> > > 
> > > Waduh buat toko aja bang wkwk🤣 Bang email lu apa? Gw wa baik baik ngak di bales wkwk
> > 
> > 
> > Kurang salam nya banh
> 
> 2

Dika sibuk gw udh sv dia entah kenapa dia bales stiker terus gw bilang sv back di read jir 🗿🤣
