### ISSUE TITLE
[EROR] stuck

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#50]
**[/index.js:463
filename = path.join(__filename, '../src/' + new Date * 1 + '.' + type.ext)
^
ReferenceError: path is not defined
at Object.hisoka.getFile (/index.js:463:9)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Object.hisoka.sendMedia (/index.js:356:21)](https://github.com/DikaArdnt/Hisoka-Morou)**

```
Jawa:
Ndang di atasi maszzeeh gen ora mati bot e karna stuck 

Indo:
bang tolong diatasi ya biar botnya ngak mati karna stuck
```

**Comment by DikaArdnt** [comment]
> **[/index.js:463 filename = path.join(__filename, '../src/' + new Date * 1 + '.' + type.ext) ^ ReferenceError: path is not defined at Object.hisoka.getFile (/index.js:463:9) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Object.hisoka.sendMedia (/index.js:356:21)](https://github.com/DikaArdnt/Hisoka-Morou)**
> 
> ```
> Jawa:
> Ndang di atasi maszzeeh gen ora mati bot e karna stuck 
> 
> Indo:
> bang tolong diatasi ya biar botnya ngak mati karna stuck
> ```

const path = require('path')
Or
import path from 'path'

**Comment by Bintangp02** [comment]
> > **[/index.js:463 filename = path.join(__filename, '../src/' + new Date * 1 + '.' + type.ext) ^ ReferenceError: path is not defined at Object.hisoka.getFile (/index.js:463:9) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Object.hisoka.sendMedia (/index.js:356:21)](https://github.com/DikaArdnt/Hisoka-Morou)**
> > ```
> > Jawa:
> > Ndang di atasi maszzeeh gen ora mati bot e karna stuck 
> > 
> > Indo:
> > bang tolong diatasi ya biar botnya ngak mati karna stuck
> > ```
> 
> const path = require('path') Or import path from 'path'

[**[ PESAN ] Mon Feb 28 2022 16:18:19 GMT+0000 (Coordinated Universal Time) .removebg
=> Dari Akbar 🎭 628xxxxxxxxx@s.whatsapp.net
=> Di Akbar 🎭 628xxxxxxx-1xxxxxx@g.us
node:internal/process/promises:265
triggerUncaughtException(err, true /* fromPromise */);
^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
code: 'ERR_UNHANDLED_REJECTION'
}**](https://github.com/DikaArdnt/Hisoka-Morou)

**Entah apa yang eror, dik (batu)**

**Comment by Bintangp02** [comment]
**Dah gw atasin sendiri udah bisa (batu)**
