### ISSUE TITLE
error session login

### ISSUE THREAD

**Issue by sanzyx** [DikaArdnt/Hisoka-Morou#59]
Connected... { isNewLogin: true, qr: undefined }
Bad Session File, Please Delete Session and Scan Again

**Comment by irham01** [comment]
scan ulang aja bang

**Comment by DineshValor** [comment]
> Connected... { isNewLogin: true, qr: undefined } Bad Session File, Please Delete Session and Scan Again

Same issue

**Comment by DineshValor** [comment]
> 

Why should its necessary?

**Comment by iamherok** [comment]
Same issue
