### ISSUE TITLE
error on getbuffer

### ISSUE THREAD

**Issue by LorranX** [DikaArdnt/Hisoka-Morou#61]
all commands that use getbuffer are having problems, the bot just dies after using some of these commands, it's hard to solve the problem because the error is not shown before the bot dies

**Comment by DikaArdnt** [comment]
> all commands that use getbuffer are having problems, the bot just dies after using some of these commands, it's hard to solve the problem because the error is not shown before the bot dies

check your apikey or check the api provider's web whether there is an error or not

**Comment by LorranX** [comment]
> > all commands that use getbuffer are having problems, the bot just dies after using some of these commands, it's hard to solve the problem because the error is not shown before the bot dies
> 
> check your apikey or check the api provider's web whether there is an error or not
> 
> Note: If that feature uses api, or just change it to Example: hisoka.sendMessage(m.chat, { image: { url: 'url Media' }}, { quoted: m })

just try to use your bot's play case

**Comment by LorranX** [comment]
> > > all commands that use getbuffer are having problems, the bot just dies after using some of these commands, it's hard to solve the problem because the error is not shown before the bot dies
> > 
> > 
> > check your apikey or check the api provider's web whether there is an error or not
> > Note: If that feature uses api, or just change it to Example: hisoka.sendMessage(m.chat, { image: { url: 'url Media' }}, { quoted: m })
> 
> just try to use your bot's play case ![image](https://user-images.githubusercontent.com/89737304/156925258-b1e84254-8192-42be-81d3-c709584a3eae.png)

it seems to be a problem with anything that needs a link
