### ISSUE TITLE
Node .

### ISSUE THREAD

**Issue by ilhamn2405** [DikaArdnt/Hisoka-Morou#62]
![Screenshot_Termux_20220305-173232](https://user-images.githubusercontent.com/43334234/156879548-de4db43e-f31d-4cfc-8cc1-566cf1a30454.png)
Knpa ini bang, nyalain ulang bot tiba" gini

**Comment by DineshValor** [comment]
Also didn't work "worker: node . --server" in heroku.

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220305-173232](https://user-images.githubusercontent.com/43334234/156879548-de4db43e-f31d-4cfc-8cc1-566cf1a30454.png) Knpa ini bang, nyalain ulang bot tiba" gini

Try this command in Termux :
npm i -g pm2 && pm2 start index.js && pm2 save && pm2 logs

**Comment by DineshValor** [comment]
> ![Screenshot_Termux_20220305-173232](https://user-images.githubusercontent.com/43334234/156879548-de4db43e-f31d-4cfc-8cc1-566cf1a30454.png) Knpa ini bang, nyalain ulang bot tiba" gini

If pm2 didn't work then try:-
$ pkg install nodejs-lts
