### ISSUE TITLE
Bang tnya dong hrus fix bagian mana, adakala nya pas udah connect di pake fitur nya pasti langsung koid, adakala nya normal itu salah apanya?

### ISSUE THREAD

**Issue by FandyyyDev** [DikaArdnt/Hisoka-Morou#69]

**Comment by FatihArridho** [comment]
Ssnya dong

**Comment by FandyyyDev** [comment]
![Screenshot_2022-03-09-10-04-42-11](https://user-images.githubusercontent.com/91331515/157364866-272525fe-80c7-4157-90f4-c64f902dc871.jpg)
Itu ss pendek nya aja 
Kdang pas lagi nge on in trs load chat nya trs pas dah lancar tinggal pake fitur pas dah di tes mati trs dipake fitur nya mati lagi intinya gitu

**Comment by FandyyyDev** [comment]
Semisalnya ada saran tolong comment ya stah 🙏

**Comment by FatihArridho** [comment]
Ntah gak tau, saya juga gitu tapi jarang atau mungkin fiturmu yg emror

**Comment by FandyyyDev** [comment]
Okelah thx dah mau bales tak close ya 🙏
