### ISSUE TITLE
Error lagi ndan

### ISSUE THREAD

**Issue by Mastrios** [DikaArdnt/Hisoka-Morou#72]
![Screenshot_2022-03-16-08-11-39](https://user-images.githubusercontent.com/99075842/158497188-8e3cb5be-5ca6-496d-b250-21f2f45afc6f.png)

Gak tau aku yang salah atau gimana, waktu ku jalankan 
`npm start / node .`

Itu muncul error yang katanya tidak ada module steno, terus ku install module steno
`npm i steno`

Ku jalani lagi ganti pindah error ke situ ndan.

Bantu ngfix nya ndan

**Comment by Bintangp02** [comment]
> ![Screenshot_2022-03-16-08-11-39](https://user-images.githubusercontent.com/99075842/158497188-8e3cb5be-5ca6-496d-b250-21f2f45afc6f.png)
> 
> Gak tau aku yang salah atau gimana, waktu ku jalankan `npm start / node .`
> 
> Itu muncul error yang katanya tidak ada module steno, terus ku install module steno `npm i steno`
> 
> Ku jalani lagi ganti pindah error ke situ ndan.
> 
> Bantu ngfix nya ndan

Coba ulangi
```
git clone https://github.com/DikaArdnt/Hisoka-Morou
cd Hisoka-Morou
pkg install yarn
yarn
npm i
node .
```
