### ISSUE TITLE
Public Self

### ISSUE THREAD

**Issue by Mastrios** [DikaArdnt/Hisoka-Morou#73]
Kalo kita sudah ketik self, kemudian ketik public tidak mau merespon ndan. Nomor sudah ku atur jadi owner, sama aja gk ada respon dari bot kalo udh self. 

Biasanya kalo kita self pasti bisa kita public, tpi kalo ini kagak, sekali self ya udh self gk bisa public, harus jalankan ulang scriptnya baru bisa public lagi :v

**Comment by DikaArdnt** [comment]
> Kalo kita sudah ketik self, kemudian ketik public tidak mau merespon ndan. Nomor sudah ku atur jadi owner, sama aja gk ada respon dari bot kalo udh self.
> 
> Biasanya kalo kita self pasti bisa kita public, tpi kalo ini kagak, sekali self ya udh self gk bisa public, harus jalankan ulang scriptnya baru bisa public lagi :v

hisoka.public = true //buat publik

case 'publik'

**Comment by FandyyyDev** [comment]
> Kalo kita sudah ketik self, kemudian ketik public tidak mau merespon ndan. Nomor sudah ku atur jadi owner, sama aja gk ada respon dari bot kalo udh self.
> 
> Biasanya kalo kita self pasti bisa kita public, tpi kalo ini kagak, sekali self ya udh self gk bisa public, harus jalankan ulang scriptnya baru bisa public lagi :v

Bisa bang lu ke nomer bot nya aja trs ketik public kan di pengaturan hisoka.public nya cuma m.key.formMe
