### ISSUE TITLE
Eror'

### ISSUE THREAD

**Issue by DkGaming12** [DikaArdnt/Hisoka-Morou#76]
![Screenshot (111)](https://user-images.githubusercontent.com/46397242/159296235-d9782958-827a-4514-b744-509157ab66db.png)

**Comment by KunzxD404** [comment]
replace the startHisoka function with

async function starthisoka() {
    const hisoka = hisokaConnect({
        logger: pino({ level: 'silent' }),
        printQRInTerminal: true,
        browser: ['hisoka Multi Device','Safari','1.0.0'],
        auth: state
    })

**Comment by Bintangp02** [comment]
**Saya harap anda mengantinya, semoga berhasil:)**
