### ISSUE TITLE
QR tidak muncul 

### ISSUE THREAD

**Issue by ilhamn2405** [DikaArdnt/Hisoka-Morou#79]
![Screenshot_Termux_20220326-172250](https://user-images.githubusercontent.com/43334234/160235284-3cd94735-2883-413e-9801-9dd29e4e66d6.png)
Knpa ni bang? Qrnya gamau muncul

**Comment by ilhamn2405** [comment]
![Screenshot_Termux_20220326-172552](https://user-images.githubusercontent.com/43334234/160235373-cc0e4a5a-480f-4d01-a48e-7e7d164e1a29.png)

**Comment by KunzxD404** [comment]
> ![Screenshot_Termux_20220326-172250](https://user-images.githubusercontent.com/43334234/160235284-3cd94735-2883-413e-9801-9dd29e4e66d6.png) Knpa ni bang? Qrnya gamau muncul

replace function startHisoka in index.js with
And please @DikaArdnt and contributors to fix it soon🐦

async function starthisoka() {
const hisoka = hisokaConnect({
logger: pino({ level: 'silent' }),
printQRInTerminal: true,
browser: ['hisoka Multi Device','Safari','1.0.0'],
auth: state
})

On index.js

**Comment by Rianfirnanda** [comment]
> > ![Screenshot_Termux_20220326-172250](https://user-images.githubusercontent.com/43334234/160235284-3cd94735-2883-413e-9801-9dd29e4e66d6.png) Knpa ni bang? Qrnya gamau muncul
> 
> replace function startHisoka in index.js with And follow my github🐦
> 
> async function starthisoka() { const hisoka = hisokaConnect({ logger: pino({ level: 'silent' }), printQRInTerminal: true, browser: ['hisoka Multi Device','Safari','1.0.0'], auth: state })

masih ngga bisa bang

**Comment by KunzxD404** [comment]
> > > ![Screenshot_Termux_20220326-172250](https://user-images.githubusercontent.com/43334234/160235284-3cd94735-2883-413e-9801-9dd29e4e66d6.png) Knpa ni bang? Qrnya gamau muncul
> > 
> > 
> > replace function startHisoka in index.js with And follow my github🐦
> > async function starthisoka() { const hisoka = hisokaConnect({ logger: pino({ level: 'silent' }), printQRInTerminal: true, browser: ['hisoka Multi Device','Safari','1.0.0'], auth: state })
> 
> masih ngga bisa bang

Mungkin ada yg salah:/

**Comment by AKUMISKIN** [comment]
Aku juga jayaj gitu :/

**Comment by AKUMISKIN** [comment]
Kayak :/ gitu

**Comment by ilhamn2405** [comment]
> > ![Screenshot_Termux_20220326-172250](https://user-images.githubusercontent.com/43334234/160235284-3cd94735-2883-413e-9801-9dd29e4e66d6.png) Knpa ni bang? Qrnya gamau muncul
> 
> replace function startHisoka in index.js with And follow my github🐦
> 
> async function starthisoka() { const hisoka = hisokaConnect({ logger: pino({ level: 'silent' }), printQRInTerminal: true, browser: ['hisoka Multi Device','Safari','1.0.0'], auth: state })



> > > ![Screenshot_Termux_20220326-172250](https://user-images.githubusercontent.com/43334234/160235284-3cd94735-2883-413e-9801-9dd29e4e66d6.png) Knpa ni bang? Qrnya gamau muncul
> > 
> > 
> > replace function startHisoka in index.js with And follow my github🐦
> > async function starthisoka() { const hisoka = hisokaConnect({ logger: pino({ level: 'silent' }), printQRInTerminal: true, browser: ['hisoka Multi Device','Safari','1.0.0'], auth: state })
> 
> masih ngga bisa bang



> Aku juga jayaj gitu :/

async function startHisoka() {
const hisoka = hisokaConnect({
logger: pino({ level: 'silent' }),
printQRInTerminal: true,
browser: ['Hisoka Multi Device','Safari','1.0.0'],
auth: state
})

Copy kode di atas, dia ada salah pengetikan, saya telah memperbaiki beberapa kata, dan kode berjalan kembali

**Comment by ilhamsk4** [comment]
hapus file device sessionya mas

**Comment by Rianfirnanda** [comment]
> hapus file device sessionya mas

Ngga ada filenya bang

**Comment by JunaGanz** [comment]
async function startHisoka() {
    let { version, isLatest } = await fetchLatestBaileysVersion()
    const hisoka = hisokaConnect({
        logger: pino({ level: 'silent' }),
        printQRInTerminal: true,
        browser: ['Hisoka Multi Device','Safari','1.0.0'],
        auth: state,
        version
    })

Coba pake async start nya pake itu

**Comment by DikaArdnt** [comment]
Mungkin karena api yang gw kasih error bang, api di version WhatsaApp index.js

**Comment by FatihArridho** [comment]
Btw dah bener ya
