### ISSUE TITLE
Masalah Database

### ISSUE THREAD

**Issue by R-TEAM94** [DikaArdnt/Hisoka-Morou#80]
@CAF-ID kan skrang dah pake mongo tuh ntar klo run heroku nge save kaga database nya? Soalnya takut aja buat fitur yang pake database" eh pas server heroku nya reset ga nge save database

**Comment by CAF-ID** [comment]
Ga :b

**Comment by R-TEAM94** [comment]
Sad :) okelah thx dah mau jawab
