### ISSUE TITLE
Cara biar ga nampilin error' body not start with prefix di display Whatsapp gmna bang?

### ISSUE THREAD

**Issue by R-TEAM94** [DikaArdnt/Hisoka-Morou#82]

**Comment by R-TEAM94** [comment]
Ksih solusi lngsung close Banh biar ga menuh"in issue 🙏

**Comment by FatihArridho** [comment]
Coba kasih ssannya

> Ksih solusi lngsung close Banh biar ga menuh"in issue pray

**Comment by R-TEAM94** [comment]
![Screenshot_2022-04-03-03-59-46-24](https://user-images.githubusercontent.com/97998325/161401054-85d50e38-8df0-44dd-b982-0ee55e2443bb.jpg)

**Comment by KunzxD404** [comment]
> ![Screenshot_2022-04-03-03-59-46-24](https://user-images.githubusercontent.com/97998325/161401054-85d50e38-8df0-44dd-b982-0ee55e2443bb.jpg)

Coba tanya yang recode:v

**Comment by pa7rickr** [comment]
> ![Screenshot_2022-04-03-03-59-46-24](https://user-images.githubusercontent.com/97998325/161401054-85d50e38-8df0-44dd-b982-0ee55e2443bb.jpg)

ubah aja yang di body '' jadi '#', kayak gini
var body = (m.mtype === 'conversation') ? m.message.conversation : (m.mtype == 'imageMessage') ? m.message.imageMessage.caption : (m.mtype == 'videoMessage') ? m.message.videoMessage.caption : (m.mtype == 'extendedTextMessage') ? m.message.extendedTextMessage.text : (m.mtype == 'buttonsResponseMessage') ? m.message.buttonsResponseMessage.selectedButtonId : (m.mtype == 'listResponseMessage') ? m.message.listResponseMessage.singleSelectReply.selectedRowId : (m.mtype == 'templateButtonReplyMessage') ? m.message.templateButtonReplyMessage.selectedId : (m.mtype === 'messageContextInfo') ? (m.message.buttonsResponseMessage?.selectedButtonId || m.message.listResponseMessage?.singleSelectReply.selectedRowId || m.text) : '#'

**Comment by DikaArdnt** [comment]
> > ![Screenshot_2022-04-03-03-59-46-24](https://user-images.githubusercontent.com/97998325/161401054-85d50e38-8df0-44dd-b982-0ee55e2443bb.jpg)
> 
> ubah aja yang di body '' jadi '#', contohnya kayak gini
> 
> var body = (m.mtype === 'conversation') ? m.message.conversation : (m.mtype == 'imageMessage') ? m.message.imageMessage.caption : (m.mtype == 'videoMessage') ? m.message.videoMessage.caption : (m.mtype == 'extendedTextMessage') ? m.message.extendedTextMessage.text : (m.mtype == 'buttonsResponseMessage') ? m.message.buttonsResponseMessage.selectedButtonId : (m.mtype == 'listResponseMessage') ? m.message.listResponseMessage.singleSelectReply.selectedRowId : (m.mtype == 'templateButtonReplyMessage') ? m.message.templateButtonReplyMessage.selectedId : (m.mtype === 'messageContextInfo') ? (m.message.buttonsResponseMessage?.selectedButtonId || m.message.listResponseMessage?.singleSelectReply.selectedRowId || m.text) : '#'

Ngga bang, biasanya itu text di message ga ke detect, result body undefined

**Comment by FatihArridho** [comment]
> > > ![Screenshot_2022-04-03-03-59-46-24](https://user-images.githubusercontent.com/97998325/161401054-85d50e38-8df0-44dd-b982-0ee55e2443bb.jpg)
> > 
> > 
> > ubah aja yang di body '' jadi '#', contohnya kayak gini
> > var body = (m.mtype === 'conversation') ? m.message.conversation : (m.mtype == 'imageMessage') ? m.message.imageMessage.caption : (m.mtype == 'videoMessage') ? m.message.videoMessage.caption : (m.mtype == 'extendedTextMessage') ? m.message.extendedTextMessage.text : (m.mtype == 'buttonsResponseMessage') ? m.message.buttonsResponseMessage.selectedButtonId : (m.mtype == 'listResponseMessage') ? m.message.listResponseMessage.singleSelectReply.selectedRowId : (m.mtype == 'templateButtonReplyMessage') ? m.message.templateButtonReplyMessage.selectedId : (m.mtype === 'messageContextInfo') ? (m.message.buttonsResponseMessage?.selectedButtonId || m.message.listResponseMessage?.singleSelectReply.selectedRowId || m.text) : '#'
> 
> Ngga bang, biasanya itu text di message ga ke detect, result body undefined
> 
> Ss an nya ga full cuma error nya aja yang di ss, penyebab error nya ga di ss jadi bingung

Betul

**Comment by R-TEAM94** [comment]
Nanti kalo dah dapet lagi error' Saia kirim
