### ISSUE TITLE
Script ini jika ingin dijual minimal ditambahin fitur yang lain dulu😄

### ISSUE THREAD

**Issue by FatihArridho** [DikaArdnt/Hisoka-Morou#85]
![IMG_20220331_144208](https://user-images.githubusercontent.com/71856084/161003880-ff5c5640-09e5-4e6a-9a6c-d6bf4b675852.jpg)

**PERHATIAN** : TIDAK PATUT DI CONTOH YA ADIK-ADIK !

**Comment by FatihArridho** [comment]
Kata dia banyak yang jual seperti itu, ntah bener atau tidaknya intinya jangan di tiru ya( ◜‿◝ )♡

**Comment by DikaArdnt** [comment]
> Kata dia banyak yg jual seperti itu, ntah bener atau tidaknya intinya jangan di tiru ya( ◜‿◝ )♡

Sangat tidak etis

**Comment by Bintangp02** [comment]
Wkwk ngab ada aja ya

**Comment by hdiiofficial** [comment]
> Kata dia banyak yg jual seperti itu, ntah bener atau tidaknya intinya jangan di tiru ya( ◜‿◝ )♡



> Kata dia banyak yg jual seperti itu, ntah bener atau tidaknya intinya jangan di tiru ya( ◜‿◝ )♡

Ngeri

**Comment by R-TEAM94** [comment]
Miris juga yak, keknya ekonomi nya sulit Ampe jual"in script ori

**Comment by hdiiofficial** [comment]
Mana bjir commitin punya gw _- cape comat camit kek mbah dukung bukannya jadi malah tambh eror:v

**Comment by KunzxD404** [comment]
> ![IMG_20220331_144208](https://user-images.githubusercontent.com/71856084/161003880-ff5c5640-09e5-4e6a-9a6c-d6bf4b675852.jpg)
> 
> **PERHATIAN** : TIDAK PATUT DI CONTOH YA ADIK-ADIK !

Di yt ada tuh sc nya dienc fitur gak sampe 200 dijual 25k mana gada yg langka🤣

**Comment by hdiiofficial** [comment]
> 

Link wkwk

**Comment by hdiiofficial** [comment]
> > ![IMG_20220331_144208](https://user-images.githubusercontent.com/71856084/161003880-ff5c5640-09e5-4e6a-9a6c-d6bf4b675852.jpg)
> > **PERHATIAN** : TIDAK PATUT DI CONTOH YA ADIK-ADIK !
> 
> Di yt ada tuh sc nya dienc fitur gak sampe 200 dijual 25k mana gada yg langka🤣

Link wkwk

**Comment by KunzxD404** [comment]
> > > ![IMG_20220331_144208](https://user-images.githubusercontent.com/71856084/161003880-ff5c5640-09e5-4e6a-9a6c-d6bf4b675852.jpg)
> > > **PERHATIAN** : TIDAK PATUT DI CONTOH YA ADIK-ADIK !
> > 
> > 
> > Di yt ada tuh sc nya dienc fitur gak sampe 200 dijual 25k mana gada yg langka🤣
> 
> Link wkwk

Cari aja di yt ada kok yg dienc dijual 25k soalnya nemunya 3 hari yg lalu tpi serius kok😅

**Comment by bolaxd** [comment]
Astagfirullah.. makan duit haram, saia klo ada orng yg minta sc mu ae gw langsung bagi github mu

**Comment by iamriz7** [comment]
LMAO banget orang-orang ini

**Comment by devinadrian** [comment]
> ![IMG_20220331_144208](https://user-images.githubusercontent.com/71856084/161003880-ff5c5640-09e5-4e6a-9a6c-d6bf4b675852.jpg)
> 
> **PERHATIAN** : TIDAK PATUT DI CONTOH YA ADIK-ADIK !

yang kea gini ma banyak wkakak, contohnya gua dulu pas belum paham language apa apa.. 

gua beli tuh script kerna ada embel embel fitur langka, yaudah gua beli trus iseng iseng bae cek satu satu file
pas di package json taunya url github masi nyangkut disono

**Comment by DikaArdnt** [comment]
> > ![IMG_20220331_144208](https://user-images.githubusercontent.com/71856084/161003880-ff5c5640-09e5-4e6a-9a6c-d6bf4b675852.jpg)
> > **PERHATIAN** : TIDAK PATUT DI CONTOH YA ADIK-ADIK !
> 
> yang kea gini ma banyak wkakak, contohnya gua dulu pas belum paham language apa apa..
> 
> gua beli tuh script kerna ada embel embel fitur langka, yaudah gua beli trus iseng iseng bae cek satu satu file pas di package json taunya url github masi nyangkut disono

Kasian kamu, turut berdukacita. Kapan tahlilan nya?
