### ISSUE TITLE
Tulung...:)

### ISSUE THREAD

**Issue by Dafatrizaa** [DikaArdnt/Hisoka-Morou#86]

**Comment by Dafatrizaa** [comment]
![Uploading Screenshot_2022-04-02-11-54-50-618_com.termux.jpg…]()

**Comment by FatihArridho** [comment]
Gajelas ssannya gada

**Comment by Dafatrizaa** [comment]
Jir masa iya bang
![Screenshot_2022-04-02-11-54-50-618_com termux](https://user-images.githubusercontent.com/95111600/161379973-d83e4af6-8268-428d-acfd-fda52a5521ba.jpg)
