### ISSUE TITLE
Ulang:v

### ISSUE THREAD

**Issue by Dafatrizaa** [DikaArdnt/Hisoka-Morou#88]
![Screenshot_2022-04-02-11-54-50-618_com termux](https://user-images.githubusercontent.com/95111600/161380032-e8e76417-74df-496e-a545-30cd186cb1ac.jpg)
Ini bang

**Comment by FatihArridho** [comment]
Coba pakai yg terbaru mungkin bisa

**Comment by Dafatrizaa** [comment]
> 

Itu EMG yg terbaru banh

**Comment by FatihArridho** [comment]
> > 
> 
> Itu EMG yg terbaru banh

![Screenshot_2022-04-05-08-50-03-07_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/71856084/161663507-1dcd90b6-6e3a-4fff-a3e1-db6393b2cf4c.jpg)

Saya aman" aja kok😁

**Comment by DikaArdnt** [comment]
> ![Screenshot_2022-04-02-11-54-50-618_com termux](https://user-images.githubusercontent.com/95111600/161380032-e8e76417-74df-496e-a545-30cd186cb1ac.jpg) Ini bang

Downgrade versi package ke yang support require
