### ISSUE TITLE
Help me:/

### ISSUE THREAD

**Issue by KunzxD404** [DikaArdnt/Hisoka-Morou#90]
![20220403_221929](https://user-images.githubusercontent.com/91834999/161434960-fc730f55-15e2-43ed-a2f7-2ead651bc17c.jpg)
 Kenapa di bot laen bisa tapi di gw napa gini mulu padahal udah pake sc asli (belum diapa apain) sama fitur chat option nya error semua di gw masalahnya cuma gw doang atau gimana:/

**Comment by DikaArdnt** [comment]
> ![20220403_221929](https://user-images.githubusercontent.com/91834999/161434960-fc730f55-15e2-43ed-a2f7-2ead651bc17c.jpg) Kenapa di bot laen bisa tapi di gw napa gini mulu padahal udah pake sc asli (belum diapa apain) sama fitur chat option nya error semua di gw masalahnya cuma gw doang atau gimana:/

Pastikan
1. Memiliki apikey yang berfungsi (jika menggunakan api)
2. Cek apakah fitur pada api tersebut terdapat error
3. Kesalahan kode

**Comment by KunzxD404** [comment]
> > ![20220403_221929](https://user-images.githubusercontent.com/91834999/161434960-fc730f55-15e2-43ed-a2f7-2ead651bc17c.jpg) Kenapa di bot laen bisa tapi di gw napa gini mulu padahal udah pake sc asli (belum diapa apain) sama fitur chat option nya error semua di gw masalahnya cuma gw doang atau gimana:/
> 
> Pastikan
> 
> 1. Memiliki apikey yang berfungsi (jika menggunakan api)
> 2. Cek apakah fitur pada api tersebut terdapat error
> 3. Kesalahan kode

Fiturnya ga pake api + kodenya asli karena make sc yg belum diapa apain

**Comment by FatihArridho** [comment]
> > > ![20220403_221929](https://user-images.githubusercontent.com/91834999/161434960-fc730f55-15e2-43ed-a2f7-2ead651bc17c.jpg) Kenapa di bot laen bisa tapi di gw napa gini mulu padahal udah pake sc asli (belum diapa apain) sama fitur chat option nya error semua di gw masalahnya cuma gw doang atau gimana:/
> > 
> > 
> > Pastikan
> > 
> > 1. Memiliki apikey yang berfungsi (jika menggunakan api)
> > 2. Cek apakah fitur pada api tersebut terdapat error
> > 3. Kesalahan kode
> 
> Fiturnya ga pake api + kodenya asli karena make sc yg belum diapa apain

Udah dijelasin sama Dika, jadi saya close.
