### ISSUE TITLE
Nanya

### ISSUE THREAD

**Issue by akmallxx** [DikaArdnt/Hisoka-Morou#92]
![IMG_20220405_110612](https://user-images.githubusercontent.com/81015426/161677240-33e59f03-2b29-4cf2-9727-3ddcc2e6a0f2.jpg)

ini knp ya klo blh tau

**Comment by DikaArdnt** [comment]
> ![IMG_20220405_110612](https://user-images.githubusercontent.com/81015426/161677240-33e59f03-2b29-4cf2-9727-3ddcc2e6a0f2.jpg)
> 
> ini knp ya klo blh tau

Update dulu Baileys nya, make versi yang di github

**Comment by akmallxx** [comment]
![IMG_20220405_112038](https://user-images.githubusercontent.com/81015426/161678245-cf9182a0-35e0-41e9-a4c1-881b131980bd.jpg)

lognya udh aman, tpi msih ga ke react

**Comment by FatihArridho** [comment]
> ![IMG_20220405_112038](https://user-images.githubusercontent.com/81015426/161678245-cf9182a0-35e0-41e9-a4c1-881b131980bd.jpg)
> 
> lognya udh aman, tpi msih ga ke react

Update dulu wa yang versi terbaru pasti bisa kok, saya aja bisa
