### ISSUE TITLE
Sticker error

### ISSUE THREAD

**Issue by peraaxd** [DikaArdnt/Hisoka-Morou#99]
![Screenshot_20220419-190044](https://user-images.githubusercontent.com/71998161/163998875-72eb22b4-6cdd-48df-8fd3-38c7f463c8f9.png)

Fitur sticker nya gk work bang

**Comment by KunzxD404** [comment]
> ![Screenshot_20220419-190044](https://user-images.githubusercontent.com/71998161/163998875-72eb22b4-6cdd-48df-8fd3-38c7f463c8f9.png)
> 
> Fitur sticker nya gk work bang

Install ffmpeg dulu di terminal nya 
Contoh termux
Install 
$pkg install ffmpeg

**Comment by peraaxd** [comment]
> > ![Screenshot_20220419-190044](https://user-images.githubusercontent.com/71998161/163998875-72eb22b4-6cdd-48df-8fd3-38c7f463c8f9.png)
> > Fitur sticker nya gk work bang
> 
> Install ffmpeg dulu di terminal nya Contoh termux Install $pkg install ffmpeg

Udah

**Comment by KunzxD404** [comment]
> > > ![Screenshot_20220419-190044](https://user-images.githubusercontent.com/71998161/163998875-72eb22b4-6cdd-48df-8fd3-38c7f463c8f9.png)
> > > Fitur sticker nya gk work bang
> > 
> > 
> > Install ffmpeg dulu di terminal nya Contoh termux Install $pkg install ffmpeg
> 
> Udah

$pkg install libwebp 
Juga

**Comment by FatihArridho** [comment]
Makanya kalau mau bisa buat sticker install ffmpeg sama libwebp.
